src/account/urls.py
from account import views

from django.urls import path


app_name = 'account'

urlpatterns = [
    path('myprofile/', views.MyProfile.as_view(), name='myprofile'),
    path('signin/', views.SignIn.as_view(), name='signin'),
    path('signout/', views.SignOut.as_view(), name='signout'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('activate/<str:username>/', views.ActivateUser.as_view(), name='activate'),
    path('password_change/<int:pk>/', views.UserPasswordChange.as_view(), name='password_change'),
    path('avatar/create/<int:pk>/', views.CreateUserAvatar.as_view(), name='avatar_create'),
    path('avatar/list/', views.AvatarList.as_view(), name='avatar_list'),
    path('avatar/active/<int:pk>/', views.SetActiveAvatar.as_view(), name='avatar_active'),
    path('avatar/delete/<int:pk>/', views.DeleteAvatar.as_view(), name='avatar_delete'),
    path('avatar/deleteall/<int:pk>/', views.DeleteAllAvatar.as_view(), name='delete_all'),
]

src/currency/urls.py
from account.views import SignUp

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.generic import TemplateView

from drf_yasg import openapi
from drf_yasg.views import get_schema_view

from rest_framework import permissions

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)


schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)

API_PREFIX = 'api/v1/'

urlpatterns = [
    path('admin/', admin.site.urls),

    path('account/', include('account.urls')),

    path('rate/', include('rate.urls')),

    path('', TemplateView.as_view(template_name='index.html'), name='index'),

    # API
    path(f'{API_PREFIX}rate/', include('rate.api.urls')),
    path(f'{API_PREFIX}account/', include('account.api.urls')),
    # API auth
    path(f'{API_PREFIX}token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path(f'{API_PREFIX}token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    # API documentation
    re_path(
        rf'^{API_PREFIX}swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'
    ),
    re_path(rf'^{API_PREFIX}swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(rf'^{API_PREFIX}redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

    # authentification app
    # path('accounts/', include('allauth.urls'))

    # django password recovery
    path('account/', include('django.contrib.auth.urls')),
    path('account/signup/', SignUp.as_view(), name='signup'),

    # API
    path('api/v1/rates/', include('rate.api.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path('__debug__', include(debug_toolbar.urls)))

handler404 = 'rate.views.handler404'
handler500 = 'rate.views.handler500'

src/rate/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views


app_name = 'rate'


urlpatterns = [
    path('list/', views.RateListView.as_view(), name='list'),
    path('contactus/list', views.ContactUsListView.as_view(), name='contactuslist'),
    path('contactus/create', views.CreateContactUsView.as_view(), name='contactuscreate'),
    path('feedback/', views.FeedbackView.as_view(), name='feedback'),
    path('showrating/', views.FeedbackShowView.as_view(), name='showrating'),
    path('error/', TemplateView.as_view(template_name='error/error_voted.html'), name='error'),
    path('sublist/', views.SubListView.as_view(), name='sublist'),
    path('dellsub/<int:pk>', views.subdel, name='dellsub'),
    path('addsubscription/', views.addsub, name='addsubscription'),
    path('latestrates/', views.LatestRates.as_view(), name='latestrates'),
    path('downloadlatestrates/', views.DownloadLatestRates.as_view(), name='downloadlatestrates'),
    path('downloadallrates/', views.DownloadAllRates.as_view(), name='downloadallrates'),
    path('deleterate/<int:pk>', views.DeleteRate.as_view(), name='deleterate'),
    path('updaterate/<int:pk>', views.UpdateRate.as_view(), name='updaterate'),
    # TODO create reate

]

src/templates/parts/filters.html
{% load crispy_forms_tags %}
<form method="get" class="uniForm">
    {{ filter.form|crispy  }}
    <button type="submit" class="btn btn-primary">
        <span class="glyphicon glyphicon-search"></span> Search
    </button>
</form>

src/templates/parts/footer.html
<header>
  
  <div class="container">
    <footer class="page-footer font-small indigo">
      <div class="footer-copyright text-center py-3">Link to repository:
        <a href="https://github.com/FoxLightning/currency"> GitHub </a>
        <br>
      </div>
    </footer>
  </div>

</header>

src/templates/parts/navbar.html
<header>
  <div class="container">
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'index' %}">Currency parser</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'rate:latestrates' %}">Latest</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'rate:list' %}">All</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'rate:showrating' %}">Rating</a>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Account
            </a>
            {% if user.is_authenticated %}
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'account:myprofile' %}">Profile</a>
              <a class="dropdown-item" href="{% url 'rate:sublist' %}">Subscription</a>
              <a class="dropdown-item" href="{% url 'rate:feedback' %}">Feedback</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'account:signout' %}">LogOut</a>
            </div>
            {% else %}
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'account:signin' %}">SignIn</a>
              <a class="dropdown-item" href="{% url 'account:signup' %}">SignUp</a>
            </div>
            {% endif %}
            <li class="nav-item">
              <div class="mb-2">
                <b-avatar src="https://placekitten.com/300/300"></b-avatar>
                <b-avatar src="https://placekitten.com/300/300" size="6rem"></b-avatar>
              </div>
            </li>
            
            {% if user.is_authenticated %}
                <img src={{ user.get_avatar_url }} width="40" height="40" class="rounded-circle">
            {% endif %}
          </li>
        </ul>
      </div>
    </nav>
  </div>
</header>

src/templates/parts/pagination.html
<nav aria-label="Page navigation example">
    <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1&{{ GET_PARAMS }}">&laquo; first</a></li>
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}&{{ GET_PARAMS }}">previous</a></li>
        {% endif %}

        

        <span class="current">
        <li class="page-item"><a class="page-link">{{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</a></li> 
        </span>

        {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}&{{ GET_PARAMS }}">next</a></li>
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}&{{ GET_PARAMS }}">last &raquo;</a></li>
        {% endif %}
    </ul>
</nav>

<form method="get">
    GOTO
    <input type="number" name="page" value="{{ number }}">
    <input type="submit" value="Submit">
    <input type="hidden" name="source" value="{{ source }}">
    <input type="hidden" name="currency" value="{{ currency  }}">
    <input type="hidden" name="sale" value="{{ sale }}">
    <input type="hidden" name="crated_day" value="{{ crated_day }}">
</form> 

src/templates/parts/test_footer.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" 
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
 <head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Фиксированный подвал</title>
  <style type="text/css">
   #content {
    width: 500px; /* Ширина слоя */
    margin: 0 auto 50px; /* Выравнивание по центру */
   }
   #footer {
    position: fixed; /* Фиксированное положение */
    left: 0; bottom: 0; /* Левый нижний угол */
    padding: 10px; /* Поля вокруг текста */
    background: #39b54a; /* Цвет фона */
    color: #fff; /* Цвет текста */
    width: 100%; /* Ширина слоя */
   }
  </style>
 </head>
 <body>
  <div id="content">
   Все перечисленные на сайте методы ловли льва являются теоретическими 
   и базируются на вычислительных методах. Автор не гарантирует 
   вашей безопасности при их использовании и снимает с себя всякую 
   ответственность за результат. 
   Помните, лев это хищник и опасное животное! 
  </div>
  <div id="footer">
   &copy; Влад Мержевич
  </div>
 </body>
</html>