src/currency/urls.py
from account.views import SignUp

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.generic import TemplateView

from drf_yasg import openapi
from drf_yasg.views import get_schema_view

from rest_framework import permissions

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)


schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)

API_PREFIX = 'api/v1/'

urlpatterns = [
    path('admin/', admin.site.urls),

    path('account/', include('account.urls')),

    path('rate/', include('rate.urls')),

    path('', TemplateView.as_view(template_name='index.html'), name='index'),

    # API
    path(f'{API_PREFIX}rate/', include('rate.api.urls')),
    path(f'{API_PREFIX}account/', include('account.api.urls')),
    # API auth
    path(f'{API_PREFIX}token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path(f'{API_PREFIX}token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    # API documentation
    re_path(
        rf'^{API_PREFIX}swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'
    ),
    re_path(rf'^{API_PREFIX}swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(rf'^{API_PREFIX}redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

    # authentification app
    # path('accounts/', include('allauth.urls'))

    # django password recovery
    path('account/', include('django.contrib.auth.urls')),
    path('account/signup/', SignUp.as_view(), name='signup'),

    # API
    path('api/v1/rates/', include('rate.api.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path('__debug__', include(debug_toolbar.urls)))

handler404 = 'rate.views.handler404'
handler500 = 'rate.views.handler500'

src/rate/api/urls.py
from rest_framework.routers import DefaultRouter

from . import views


app_name = 'api-rate'

router = DefaultRouter()
router.register('rates', views.RateAPIViewSet, basename='rate')

urlpatterns = router.urls

src/rate/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views


app_name = 'rate'


urlpatterns = [
    path('list/', views.RateListView.as_view(), name='list'),
    path('contactus/list', views.ContactUsListView.as_view(), name='contactuslist'),
    path('contactus/create', views.CreateContactUsView.as_view(), name='contactuscreate'),
    path('feedback/', views.FeedbackView.as_view(), name='feedback'),
    path('showrating/', views.FeedbackShowView.as_view(), name='showrating'),
    path('error/', TemplateView.as_view(template_name='error/error_voted.html'), name='error'),
    path('sublist/', views.SubListView.as_view(), name='sublist'),
    path('dellsub/<int:pk>', views.subdel, name='dellsub'),
    path('addsubscription/', views.addsub, name='addsubscription'),
    path('latestrates/', views.LatestRates.as_view(), name='latestrates'),
    path('downloadlatestrates/', views.DownloadLatestRates.as_view(), name='downloadlatestrates'),
    path('downloadallrates/', views.DownloadAllRates.as_view(), name='downloadallrates'),
    path('deleterate/<int:pk>', views.DeleteRate.as_view(), name='deleterate'),
    path('updaterate/<int:pk>', views.UpdateRate.as_view(), name='updaterate'),
    # TODO create reate

]

src/rate/models.py
from django.db import models
from django.utils.timezone import now

from . import choices


class Rate(models.Model):
    currency = models.PositiveSmallIntegerField(choices=choices.CURRENCY_CHOICES, verbose_name='Currency')
    source = models.PositiveSmallIntegerField(choices=choices.SOURCE_CHOICES, verbose_name='Bank')
    buy = models.DecimalField(max_digits=6, decimal_places=2, verbose_name='Buy')
    sale = models.DecimalField(max_digits=6, decimal_places=2, verbose_name='Sale')
    created = models.DateTimeField(verbose_name='Update time', default=now)

    def __str__(self):
        # max recursion depth if i try to use get_source_display
        # по индексу обращаться тоже не особо круто, TODO довести до ума
        return f"{choices.SOURCE_CHOICES[self.source-1][0]} {choices.CURRENCY_CHOICES[self.currency-1]}"

    class Meta:
        verbose_name = "Rate"
        verbose_name_plural = "Rates"
        permissions = [
            ("full_edit", "full edit")
        ]


class ContactUs(models.Model):
    email = models.EmailField()
    subject = models.CharField(max_length=128)
    massage = models.TextField()

    def __str__(self):
        return self.subject

    class Meta:
        verbose_name = "Massage"
        verbose_name_plural = "Massages"


class Feedback(models.Model):
    rating = models.PositiveSmallIntegerField(choices=choices.OPTIONS)
    user = models.OneToOneField('account.User', on_delete=models.CASCADE)

    def __str__(self):
        return str(self.rating)

    class Meta:
        verbose_name = "Feedback"
        verbose_name_plural = "Feedbacks"


class Subscription(models.Model):
    banks = models.PositiveSmallIntegerField(choices=choices.SOURCE_CHOICES)
    user = models.ForeignKey('account.User', on_delete=models.CASCADE)

src/rate/forms.py
from django import forms

from rate import choices


OPTIONS = ((1, 1), (2, 2), (3, 3), (4, 4), (5, 5),
           (6, 6), (7, 7), (8, 8), (9, 9), (10, 10),)


class SubscriptionForm(forms.Form):
    banks = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple, choices=choices.SOURCE_CHOICES)

src/rate/api/views.py
from rate.api.serializers import RateSerializer
from rate.models import Rate

from rest_framework import viewsets


class RateAPIViewSet(viewsets.ModelViewSet):
    queryset = Rate.objects.all().order_by('-id')
    serializer_class = RateSerializer

src/rate/views.py
from django.db.models import Avg
from django.http import HttpResponse
from django.shortcuts import redirect, render, render_to_response
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView, TemplateView, UpdateView, View

from django_filters.views import FilterView

from rate.filters import RateFilter

from .forms import SubscriptionForm
from .models import ContactUs, Feedback, Rate, Subscription
from .tasks import send_email_async
from .utils import create_xml, last_rates


class RateListView(FilterView):
    queryset = Rate.objects.all()
    paginate_by = 10
    filterset_class = RateFilter

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        for key, value in self.request.GET.items():
            context[key] = value
        context['GET_PARAMS'] = '&'.join(
            f'{key}={value}'
            for key, value in self.request.GET.items()
            if key != 'page'
        )
        context['object_count'] = context['object_list'].count()
        return context


class ContactUsListView(ListView):
    queryset = ContactUs.objects.all()


class CreateContactUsView(CreateView):
    success_url = reverse_lazy('index')
    model = ContactUs
    fields = ('email', 'subject', 'massage')

    def form_valid(self, form):
        if form.is_valid():
            data = form.cleaned_data
            send_email_async.delay(data['subject'], f"sander:{data['email']}\n{data['massage']}")
        return super().form_valid(form)


class FeedbackView(CreateView):
    success_url = reverse_lazy('index')
    model = Feedback
    fields = ('rating',)

    def get_context_data(self, **kwargs):
        if 'form' not in kwargs:
            kwargs['form'] = self.get_form()
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        if Feedback.objects.filter(user_id=self.request.user.id).exists():
            return redirect('rate:error')
        else:
            Feedback.objects.create(
                rating=form.cleaned_data['rating'],
                user_id=self.request.user.id,
            )
            return redirect('rate:showrating')


class FeedbackShowView(TemplateView):
    template_name = 'rate/feedback_list.html'

    def get_context_data(self, **kwargs):
        kwargs['avg'] = Feedback.objects.all().aggregate(Avg('rating'))['rating__avg']
        kwargs['count'] = Feedback.objects.all().count()
        return super().get_context_data(**kwargs)


class ErrorView(TemplateView):
    template_name = 'rate/error.html'

    def get_context_data(self, **kwargs):
        kwargs['error'] = 'You are allready voted'
        return super().get_context_data(**kwargs)


class SubListView(ListView):
    queryset = None
    pk_url_kwarg = ('pk', 'id')

    def get_queryset(self):
        if self.queryset is None:
            queryset = Subscription.objects.filter(user=self.request.user)
        return queryset


# TODO rework
def subdel(request, pk):
    Subscription.objects.filter(id=pk, user=request.user).delete()
    return redirect('rate:sublist')


class AddSubView(CreateView):
    success_url = reverse_lazy('rate:sublist')
    model = Subscription
    fields = ('banks',)
    template_name = 'rate/addsubscription_create.html'

    def form_valid(self, form):
        bunks = form.cleaned_data['banks']
        self.model.objects.create(
            user=self.request.user,
            banks=bunks,
            )
        return redirect('rate:sublist')


# TODO rework
def addsub(request):
    form = SubscriptionForm(request.POST or None)
    context = {'form': form}
    if request.POST:
        if form.is_valid():
            user = request.user
            choices = form.cleaned_data.get("banks")
            sub_banks = [i.banks for i in Subscription.objects.filter(user=user)]
            for bank in map(int, choices):
                if bank not in sub_banks:
                    Subscription.objects.create(
                        user=user,
                        banks=bank,
                    )
        return redirect('rate:sublist')
    return render(
        request,
        'rate/addsubscription_create.html',
        context=context
    )


class LatestRates(View):
    def get(self, request):
        context = {'rate_list': last_rates()}
        return render(request, 'rate/latest-rates.html', context=context)


class DownloadLatestRates(View):
    def get(self, request):
        file = create_xml(last_rates())
        response = HttpResponse(file.getvalue(), content_type='application/xml')
        response['Content-Disposition'] = 'attachment; filename=rate_list.xml'
        return response


class DownloadAllRates(View):
    def get(self, request):
        file = create_xml(Rate.objects.all())
        response = HttpResponse(file.getvalue(), content_type='application/xml')
        response['Content-Disposition'] = 'attachment; filename=rate_list.xml'
        return response


class DeleteRate(DeleteView):
    queryset = Rate.objects.all()
    success_url = reverse_lazy('rate:list')

    def delete(self, request, *args, **kwargs):
        if request.user.is_superuser:
            return super().delete(self, request, *args, **kwargs)


class UpdateRate(UpdateView):
    model = Rate
    success_url = reverse_lazy('rate:list')
    fields = ['currency', 'source', 'buy', 'sale', 'created']

    def form_valid(self, form):
        if self.request.user.is_superuser:
            return super().form_valid(form)


def handler404(request, exception):
    response = render_to_response('error/404.html', {})
    response.status_code = 404
    return response


def handler500(request):
    response = render_to_response('/error/500.html', {})
    response.status_code = 500
    return render(response, 'rate/500.html', locals())

src/rate/templates/rate/addsubscription_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="row">
    <div class="col">
      <br><br><br>
      <form method="POST" class="bootstrap4"> 
        {% csrf_token %} 
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Add</button>
      </form> 
    </div>
  </div>
{% endblock content %}

src/rate/templates/rate/contactus_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="row">
    <div class="col">
      <form action="{% url 'rate:contactuscreate' %}" method='POST' class="bootstrap4">
        <div class="form-group">
          <br>
          {% csrf_token %}
          {{ form|crispy }}
        </div>
        <button type="submit" class="btn btn-primary">Send</button>
      </form>
    </div>
  </div>
{% endblock content %}

src/rate/templates/rate/contactus_list.html
{% extends 'base.html' %}


{% block content%}
  <div class='row'>
    <div class='col'>
      <table class="table">
        <thead>
          <tr>
            <th scope="col">№</th>
            <th scope="col">Email</th>
            <th scope="col">Subject</th>
            <th scope="col">Massage</th>
          </tr>
        </thead>
        <tbody>
          {% for row in contactus_list %}
          <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ row.email }}</td>
            <td>{{ row.subject }}</td>
            <td>{{ row.massage }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% endblock content%}

src/rate/templates/rate/feedback_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block content %}
  <div class="row">
    <div class="col">
    </div>
    <div class="col">
      <br><br><br>
      <form action="{% url 'rate:feedback' %}" method='POST' class="bootstrap4">
        {% csrf_token %} 
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Ok</button>
      </form>
    </div>
    <div class="col">
    </div>
  </div>
{% endblock content %}

src/rate/templates/rate/feedback_list.html
{% extends 'base.html' %}

{% block content %}
  <div class="row">
    <div class="col">
      <form action="{% url 'rate:feedback' %}" method='POST'>
        {% csrf_token %} 
        <br>
        <br>
        number of feedbacks: {{ count }}
        <h1>AVG rating: {{ avg }} (10)</h1>
      </form>
    </div>
  </div>
{% endblock content %}

src/rate/templates/rate/hw14.html
{% extends 'base.html' %}

{% block content%}
  <div class='row'>
    <div class='col'>
      <a href="{% url 'rate:downloadallrates' %}">Download</a>
      <table class="table">
        <thead>
          <tr>
            <th scope="col">№</th>
            <th scope="col">Currency</th>
            <th scope="col">Source</th>
            <th scope="col">Buy</th>
            <th scope="col">Sale</th>
            <th scope="col">Last update</th>
          </tr>
        </thead>
        <tbody>
          {% for row in rate_list %}
          <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ row.get_currency_display }}</td>
            <td>{{ row.get_source_display }}</td>
            <td>{{ row.buy }}</td>
            <td>{{ row.sale }}</td>
            <td>{{ row.created }}</td>

          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% endblock content%}

src/rate/templates/rate/latest-rates.html
{% extends 'base.html' %}

{% block content%}
  <div class='row'>
    <div class='col'>
      <a href="{% url 'rate:downloadlatestrates' %}">Download</a>
      <table class="table">
        <thead>
          <tr>
            <th scope="col">№</th>
            <th scope="col">Currency</th>
            <th scope="col">Source</th>
            <th scope="col">Buy</th>
            <th scope="col">Sale</th>
            <th scope="col">Last update</th>
          </tr>
        </thead>
        <tbody>
          {% for row in rate_list %}
          <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ row.get_currency_display }}</td>
            <td>{{ row.get_source_display }}</td>
            <td>{{ row.buy }}</td>
            <td>{{ row.sale }}</td>
            <td>{{ row.created }}</td>

          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% endblock content%}

src/rate/templates/rate/rate_confirm_delete.html
{% extends 'base.html' %}

{% block content%}

<form method="post">{% csrf_token %} 
    <p>Are you sure you want to delete "{{ object }}"?</p> 
    <button type="submit" class="btn btn-primary">Delete</button>
</form> 

{% endblock content%}

src/rate/templates/rate/rate_filter.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
  <div class='row'>
    <div class='col-2'>
      {% include 'parts/filters.html' %}
      <br>
      <br>
      <a href="{% url 'rate:downloadallrates' %}" class="btn btn-primary btn-sm active" role="button" aria-pressed="true">Download</a>
    </div>
    <div class='col-10'>
  
      <table class="table">
        <thead>
          <tr>
            <th scope="col">id</th>
            <th scope="col">Currency</th>
            <th scope="col">Source</th>
            <th scope="col">Buy</th>
            <th scope="col">Sale</th>
            <th scope="col">Last update</th>
            {% if user.is_superuser %}
            <th scope="col">
              <a href="" class="btn btn-primary btn-sm active" role="button" aria-pressed="true"> &#10133 </a>
                <a href="{% url 'rate:downloadallrates' %}" class="btn btn-primary btn-sm active" role="button" aria-pressed="true">&#128190;</a>
              </th>
            {% endif %}
          </tr>
        </thead>
        <tbody>
          {% for row in rate_list %}
          <tr>
            <td>{{ row.id }}</td>
            <td>{{ row.get_currency_display }}</td>
            <td>{{ row.get_source_display }}</td>
            <td>{{ row.buy }}</td>
            <td>{{ row.sale }}</td>
            <td>{{ row.created }}</td>
            {% if user.is_superuser %}
              <td>
                <a href="{% url 'rate:updaterate' row.id %}" class="btn btn-warning btn-sm active" role="button" aria-pressed="true">✏</a>
                <a href="{% url 'rate:deleterate' row.id %}" class="btn btn-danger btn-sm active" role="button" aria-pressed="true">🗑</a>
              </td>
            {% endif %}
  
          </tr>
          {% endfor %}
        </tbody>
      </table>
      
      {% include 'parts/pagination.html' %}




    </div>
  </div>
{% endblock content %}

src/rate/templates/rate/rate_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="row">
    <div class="col">
      <br><br><br>
      <form action="{% url 'rate:updaterate' rate.id %}" method='POST' class="bootstrap4">
        {% csrf_token %} 
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Update</button>
      </form>
    </div>
  </div>
{% endblock content %}

src/rate/templates/rate/rate_list.html
{% extends 'base.html' %}

{% block content%}
  <div class='row'>
    <div class='col'>
      <a href="{% url 'rate:downloadallrates' %}" class="btn btn-primary btn-sm active" role="button" aria-pressed="true">Download</a>
      <table class="table">
        <thead>
          <tr>
            <th scope="col">№</th>
            <th scope="col">Currency</th>
            <th scope="col">Source</th>
            <th scope="col">Buy</th>
            <th scope="col">Sale</th>
            <th scope="col">Last update</th>
            {% if user.is_superuser %}
            <th scope="col">id</th>
            <th scope="col">
              <a href="" class="btn btn-primary btn-sm active" role="button" aria-pressed="true"> &#10133 </a>
                <a href="{% url 'rate:downloadallrates' %}" class="btn btn-primary btn-sm active" role="button" aria-pressed="true">&#128190;</a>
              </th>
            {% endif %}
          </tr>
        </thead>
        <tbody>
          {% for row in rate_list %}
          <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ row.get_currency_display }}</td>
            <td>{{ row.get_source_display }}</td>
            <td>{{ row.buy }}</td>
            <td>{{ row.sale }}</td>
            <td>{{ row.created }}</td>
            {% if user.is_superuser %}
              <td>{{ row.id }}</td>
              <td>
                <a href="{% url 'rate:updaterate' row.id %}" class="btn btn-warning btn-sm active" role="button" aria-pressed="true">✏</a>
                <a href="{% url 'rate:deleterate' row.id %}" class="btn btn-danger btn-sm active" role="button" aria-pressed="true">🗑</a>
              </td>
            {% endif %}

          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% endblock content%}

src/rate/templates/rate/rating.html
{% extends 'base.html' %}

{% block content %}
  <div class="row">
    <div class="col">
      <form action="{% url 'rate:feedback' %}" method='POST'>
        {% csrf_token %} 
        <br>
        <br>
        <h1>AVG rating: {{ rating }} (10)</h1>
      </form>
    </div>
  </div>
{% endblock content %}

src/rate/templates/rate/subscription_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block content %}
  <div class="row">
    <div class="col">
      <br><br><br>
      <form action="{% url 'rate:subscription' %}" method='POST' class="bootstrap4">
        {% csrf_token %} 
        {{ form|crispy}}

        <button type="submit" class="btn btn-primary">Primary</button>
      </form>
    </div>
  </div>
{% endblock content %}

src/rate/templates/rate/subscription_list.html
{% extends 'base.html' %}

{% block content%}
  <div class='row'>
    <div class='col'>
      <table class="table">
        <br>
        <thead>
          <tr>
            <th scope="col">№</th>
            <th scope="col">Bank</th>
            <th scope="col">
              <a href="{% url 'rate:addsubscription' %}">Add</a>
            </th>
          </tr>
        </thead>
        <tbody>
          {% for row in subscription_list %}
          <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ row.get_banks_display }}</td>
            <td>
              <a href="{% url 'rate:dellsub' row.id %}">Delete</a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% endblock content%}